const galleryCatalog = {
    'image1': [
        "Picture1.png",
    ],
    'image2': [
        "Picture1.png",
    ],
};

const galleryDirMapping = {
    'gallery1': 'image1',
    'gallery2': 'image2',
};

// This file is generated by update_gallery_catalog.py
// Run: python update_gallery_catalog.py