const galleryCatalog = {
    'rzezby': [
        "Picture1.png",
    ],
    'medale': [
        "Picture1 copy 2.png",
        "Picture1 copy.png",
        "Picture1.png",
        "pobrane (1).jpg",
        "pobrane (2).jpg",
        "pobrane (3).jpg",
        "pobrane (4).jpg",
        "pobrane.jpg",
    ],
};

const galleryDirMapping = {
    'rzezby': 'rzezby',
    'medale': 'medale',
};

// This file is generated by update_gallery_catalog.py
// Run: python update_gallery_catalog.py