const galleryCatalog = {
    'rzezby': [
        "Rectangle 1.png",
        "Rectangle 2.png",
        "Rectangle 3.png",
        "Rectangle 4.png",
        "Rectangle 5.png",
        "Rectangle 6.png",
        "Rectangle 7.png",
    ],
    'medale': [
        "DSC00151.png",
        "DSC00169.png",
        "DSC00170.png",
        "Frame 61.png",
        "Frame 62.png",
        "Rectangle 37.png",
        "Rectangle 38.png",
        "Rectangle 42.png",
        "Rectangle 43.png",
        "medal.png",
    ],
};

const galleryDirMapping = {
    'rzezby': 'rzezby',
    'medale': 'medale',
};

// This file is generated by update_gallery_catalog.py
// Run: python update_gallery_catalog.py