from pathlib import Path
import json

BASE_DIR = Path(__file__).resolve().parent
GALLERY_DIR = BASE_DIR / 'images'
CATALOG_FILE = BASE_DIR / 'js' / 'galleryCatalog.js'

FOLDERS = {
    'gallery1': 'image1',
    'gallery2': 'image2',
}

EXTENSIONS = {'.jpg', '.jpeg', ".png"}


def scan_folder(folder_path):
    if not folder_path.exists() or not folder_path.is_dir():
        return []
    return sorted(
        [file.name for file in folder_path.iterdir() if file.suffix.lower() in EXTENSIONS and file.is_file()]
    )


def build_catalog():
    catalog = {}
    for gallery_key, folder_name in FOLDERS.items():
        folder_path = GALLERY_DIR / folder_name
        catalog[folder_name] = scan_folder(folder_path)
    return catalog


def format_catalog_js(catalog):
    lines = [
        'const galleryCatalog = {',
    ]

    for folder_name, files in catalog.items():
        lines.append(f"    '{folder_name}': [")
        for file_name in files:
            lines.append(f'        "{file_name}",')
        lines.append('    ],')

    lines.append('};')
    lines.append('')
    lines.append('const galleryDirMapping = {')
    for gallery_key, folder_name in FOLDERS.items():
        lines.append(f"    '{gallery_key}': '{folder_name}',")
    lines.append('};')
    lines.append('')
    lines.append('// This file is generated by update_gallery_catalog.py')
    lines.append('// Run: python update_gallery_catalog.py')
    return '\n'.join(lines)


def write_catalog_js(content):
    CATALOG_FILE.write_text(content, encoding='utf-8')


if __name__ == '__main__':
    catalog = build_catalog()
    js_content = format_catalog_js(catalog)
    write_catalog_js(js_content)
    print(f'Updated {CATALOG_FILE}')
